name: Torch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_0
  - anyio=4.7.0=py310haa95532_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h827c3e9_1
  - asttokens=3.0.0=py310haa95532_0
  - async-lru=2.0.4=py310haa95532_0
  - attrs=24.3.0=py310haa95532_0
  - babel=2.16.0=py310haa95532_0
  - beautifulsoup4=4.13.4=py310haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py310haa95532_0
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.8.3=h4c7d964_0
  - cairo=1.16.0=he9e932c_7
  - certifi=2025.8.3=py310haa95532_0
  - cffi=1.17.1=py310h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - cuda-cccl=13.0.50=h23517cc_1
  - cuda-cccl_win-64=13.0.50=hc667259_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.39=0
  - cuda-opencl-dev=13.0.39=0
  - cuda-profiler-api=13.0.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.11=py310h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - eigen=3.4.0=h91493d7_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py310haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h8d14728_0
  - gflags=2.2.2=he0c23c2_1005
  - giflib=5.2.2=h7edc060_0
  - git=2.51.0=h57928b3_1
  - glog=0.5.0=h4797de2_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=h1f81b68_0
  - h11=0.16.0=py310haa95532_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - httpcore=1.0.9=py310haa95532_0
  - httpx=0.28.1=py310haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py310haa95532_1
  - ipython=8.30.0=py310haa95532_0
  - ipywidgets=8.1.5=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.25=py310haa95532_0
  - jsonschema=4.25.0=py310haa95532_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter=1.1.1=py310haa95532_0
  - jupyter-lsp=2.2.5=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_console=6.6.3=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - jupyter_events=0.12.0=py310haa95532_0
  - jupyter_server=2.16.0=py310haa95532_0
  - jupyter_server_terminals=0.5.3=py310haa95532_0
  - jupyterlab=4.4.4=py310haa95532_0
  - jupyterlab_pygments=0.3.0=py310haa95532_0
  - jupyterlab_server=2.27.3=py310haa95532_0
  - jupyterlab_widgets=3.0.15=py310haa95532_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libavif=1.3.0=hf2698fe_0
  - libavif16=1.3.0=hf2698fe_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.0.35=0
  - libcurand-dev=10.4.0.35=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h2466b09_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libprotobuf=5.29.3=h65a231f_1
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.7.0=h404307b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hcfcfb64_1
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mistune=3.1.2=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - nbclient=0.10.2=py310haa95532_0
  - nbconvert=7.16.6=py310haa95532_0
  - nbconvert-core=7.16.6=py310haa95532_0
  - nbconvert-pandoc=7.16.6=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - notebook=7.4.4=py310haa95532_0
  - notebook-shim=0.2.4=py310haa95532_0
  - numpy=2.0.1=py310h055cbcc_1
  - numpy-base=2.0.1=py310h65a83cf_1
  - opencv=4.10.0=py310h28596fa_7
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.2=h725018a_0
  - overrides=7.4.0=py310haa95532_0
  - packaging=25.0=py310haa95532_0
  - pandoc=2.12=haa95532_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py310haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py310hb328d1f_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.3.7=py310haa95532_0
  - prometheus_client=0.21.1=py310haa95532_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h827c3e9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py310haa95532_0
  - pyqt=6.7.1=py310h378bd72_2
  - pyqt6-sip=13.9.1=py310h02ab6af_2
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-fastjsonschema=2.20.0=py310haa95532_0
  - python-json-logger=3.2.1=py310haa95532_0
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=311=py310h885b0b7_0
  - pywinpty=2.0.15=py310h72d21ff_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=26.2.0=py310h5da7b33_0
  - qtbase=6.7.3=hd088775_4
  - qtconsole=5.6.1=py310haa95532_1
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtpy=2.4.1=py310haa95532_0
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - rav1e=0.7.1=ha073cba_3
  - referencing=0.30.2=py310haa95532_0
  - requests=2.32.4=py310haa95532_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rpds-py=0.22.3=py310h636fa0f_0
  - send2trash=1.8.2=py310haa95532_1
  - setuptools=78.1.1=py310haa95532_0
  - sip=6.10.0=py310h5da7b33_0
  - six=1.17.0=py310haa95532_0
  - sniffio=1.3.0=py310haa95532_0
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=3.0.2=he0c23c2_0
  - sympy=1.13.3=py310haa95532_1
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py310haa95532_0
  - tinycss2=1.4.0=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py310haa95532_0
  - tornado=6.5.1=py310h827c3e9_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.12.2=py310haa95532_0
  - typing_extensions=4.12.2=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py310haa95532_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=1.8.0=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - widgetsnbextension=4.0.13=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.59.1
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - matplotlib==3.10.5
      - nibabel==5.3.2
      - opencv-python==4.12.0.88
      - pandas==2.3.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pytz==2025.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - simsimd==6.5.1
      - stringzilla==3.12.6
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
